[build]
target = "index.html"
dist = "dist"
release = false
[serve]
port = 8080
open = false

[watch]
watch = ["src", "Cargo.toml", "index.html"]

[tools]
wasm_bindgen = "0.2.125"
wasm_opt = "version_123"
