name: Despliegue web

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Construir sitio WASM
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libasound2-dev libudev-dev

      - name: Instalar Trunk
        run: cargo install trunk --locked

      - name: Construir WebAssembly
        run: trunk build --release

      - name: Publicar en GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
